[package]
name = "organizze_join_tables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
clap = { version = "4.3.5", features = ["derive"] }
